Add delivery size threshold
workato/ruby-kafka pull request #3
Opened 2023-05-16 09:55 UTC by yboulkaid

Background:

When producing messages asynchronously, we send messages in batches triggered by:
- a polling duration (`delivery_interval`)
- a number of messages (`delivery_threshold`)

However, Kafka brokers have a maximum size they allow a batch to be when accepting them (defaults to 1 Mb). When a batch is larger than this size it gets rejected by the broker and we start getting `MessageSizeTooLarge` exceptions, which can cause outages as it's impossible to recover from these without losing data.

To mitigate this, this PR adds a third type of threshold based on batch size that can trigger an early sending of a batch to the broker.

The plan is to set this to ~70/80% of the maximum allowed batch size, so that we preemptively send batches to the broker before we are at risk of the batches getting too large.

2023-05-16 14:28 UTC, climber73 approved these changes

2023-05-16 14:28 UTC, climber73 commented on lib/kafka/async_producer.rb
> +    def initialize(sync_producer:, max_queue_size: 1000, delivery_threshold: 0, delivery_interval: 0, max_retries: -1, retry_backoff: 0, instrumenter:, logger:, delivery_size_threshold_bytes: -1)
please, add the param description for the new arg

2023-05-16 14:28 UTC, climber73 commented on lib/kafka/async_producer.rb
> +          @producer.buffer_bytesize >= @delivery_size_threshold_bytes
does this `buffer_bytesize` correspond to the size of the batch going to be sent to broker?

2023-05-17 10:26 UTC, yboulkaid commented on lib/kafka/async_producer.rb
> +          @producer.buffer_bytesize >= @delivery_size_threshold_bytes
Not exactly, but close. `buffer_bytesize` corresponds to the size of the messages in the async producer buffer, which we try to completely flush every time we send its contents to the broker.

In most cases, the buffer is not backlogged and `buffer_bytesize` will be the size of the batch going to be sent to the broker.

However, in cases where the buffer is backlogged, then we will still try to send its full contents to the kafka broker. The batches are then split by [topic and partition](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/produce_operation.rb#L111)

This means that this PR provides an extra safety for the buffer growing too large, but does not guarantee that we will _never_ try to send batches that are too large :/

2023-05-17 10:28 UTC, yboulkaid commented on lib/kafka/async_producer.rb
> +    def initialize(sync_producer:, max_queue_size: 1000, delivery_threshold: 0, delivery_interval: 0, max_retries: -1, retry_backoff: 0, instrumenter:, logger:, delivery_size_threshold_bytes: -1)
Done in https://github.com/workato/ruby-kafka/pull/3/commits/b9b1cdf0fd900b5536df3127d4bb0907c7326923

2023-05-17 14:45 UTC, climber73 approved these changes

2023-05-17 14:45 UTC, climber73 commented on lib/kafka/async_producer.rb
> +          @producer.buffer_bytesize >= @delivery_size_threshold_bytes
Can you please add this thorough description as a code comment? I  believe it will help somebody sometime

2023-05-23 16:19 UTC, vladkorobkov commented on lib/kafka/async_producer.rb
> +          @producer.buffer_bytesize >= @delivery_size_threshold_bytes
@yboulkaid could you please explain, what does "buffer is/is not backlogged" mean?

2023-05-25 08:15 UTC, yboulkaid commented on lib/kafka/async_producer.rb
> +          @producer.buffer_bytesize >= @delivery_size_threshold_bytes
Sure! By not backlogged I mean that we are able to send all messages in the async buffer whenever we produce a batch. This is the happy path.

An example of a "backlogged" buffer is for example if Kafka is unresponsive and the message producing fails. Then we would accumulate messages in the buffer, potentially more than the `buffer_bytesize`. And if we have a large number of messages going to the same topic _and partition_ we are still technically at risk of `MessageSizeTooLarge`.

This PR would significantly decrease our exposure to this situation though. Especially coupled with the change to [make customer logs messages smaller in size](https://github.com/workato/workato/pull/36077).

2023-05-25 12:45 UTC, abit2 requested changes

2023-05-25 12:45 UTC, abit2 commented on lib/kafka/async_producer.rb
> +              deliver_messages if size_threshold_reached?
I think it look promising, nice work. 👏🏼  If i am understanding it correctly.
There might be one case that i think will make it fail:
Let say the allowed size accepted by the broker is 1MB

- Say the delivery_size_threshold_bytes is 900KB
- State of the queue is say 870 KB,
- Time is configured to flush 1 second.

Next message that we added will be of payload say 140KB, according to flow of the code the sync producer will enqueue the msg making the size of the buffer 1100KB,
In the next step we see the size threshold is exceeded so the flush/delivery of messages will occur but it will not be accepted by the broker.

It might be better to add the threshold check in the sync producer, and flushing if the size limit is exceeded

2023-05-25 13:19 UTC, yboulkaid commented on lib/kafka/async_producer.rb
> +              deliver_messages if size_threshold_reached?
Yes you are correct, if we are dealing with large messages and a large `delivery_size_threshold_bytes` we are still at risk of triggering this failure mode.

To counteract this, we should try to work with relatively small message sizes and a `delivery_size_threshold_bytes` that's around 70% of max batch size.

> It might be better to add the threshold check in the sync producer, and flushing if the size limit is exceeded

This check is [already done](https://github.com/workato/ruby-kafka/blob/b9b1cdf0fd900b5536df3127d4bb0907c7326923/lib/kafka/producer.rb#L218-L221) in the sync producer, but the reaction is to fail with a `BufferOverflow` :/ 

I can look into changing the logic in the sync producer as an additional measure if we deem that necessary, but would still like to merge this PR as-is to keep its scope small. What do you think?

2023-05-25 15:31 UTC, abit2 commented on lib/kafka/async_producer.rb
> +              deliver_messages if size_threshold_reached?
i would suggest handling the buffer overflow error
something like 
- flushing the current queue
- retry with some backoff.

Yes dealing with large message is the culprit for sure, but i think the library should be agonistic of such fine tune config as much as possible.
The fine tuning should be left to the developer using the gem.
I agree it can be achieved if we are extra careful i would suggest adding some documentation mentioning we are not handling this case if we go forward with current implementation.

2023-05-26 09:29 UTC, yboulkaid commented on lib/kafka/async_producer.rb
> +              deliver_messages if size_threshold_reached?
> i would suggest handling the buffer overflow error
> something like
> - flushing the current queue
> - retry with some backoff.

The problem is that when the buffer is too large for the broker, flushing the queue will fail with the same error (we're trying to send the same messages) and we will be stuck in a loop. If we want to be properly resilient to this, we would need a mechanism to **partially** flush the queue in case we get a `MessageSizeTooLarge` error.

Because this is one extra level of complexity above the work in this PR, I propose merging the current implementation first, then looking into the need for the partial flush in a follow-up PR.

Otherwise I agree that this library is fragile and it's up to the implementer to make sure the settings are fine-tuned to avoid sending batches that are too large, I don't like it either :/

2023-05-26 14:58 UTC, abit2 commented on lib/kafka/async_producer.rb
> +              deliver_messages if size_threshold_reached?
Maybe i am wrong but i don't agree with what you said I think this is how it is handled in the sync producer layer.

As i understood the code I think the message is first pushed to the pending buffer here. 
https://github.com/workato/ruby-kafka/blob/b9b1cdf0fd900b5536df3127d4bb0907c7326923/lib/kafka/producer.rb#L230

And if then the check about the current_buffer_size+msg.size is done here which should return the error that we can handle.

https://github.com/workato/ruby-kafka/blob/b9b1cdf0fd900b5536df3127d4bb0907c7326923/lib/kafka/producer.rb#L218-L221


The messages are moved from pending queue to buffer when the delivery method is called by the producer
https://github.com/workato/ruby-kafka/blob/b9b1cdf0fd900b5536df3127d4bb0907c7326923/lib/kafka/producer.rb#L450-L455

https://github.com/workato/ruby-kafka/blob/b9b1cdf0fd900b5536df3127d4bb0907c7326923/lib/kafka/producer.rb#L254-L270


https://github.com/workato/ruby-kafka/blob/b9b1cdf0fd900b5536df3127d4bb0907c7326923/lib/kafka/async_producer.rb#L292-L298


So basically, the error returned is before it is added to the pending buffer, so we can flush and retry to add it. Please let me know if i missed something. 🙏🏼

2023-07-31 10:57 UTC, yboulkaid commented
This was a configuration error in the end, see https://github.com/workato/workato/pull/36784

2023-07-31 10:57 UTC, closed without merging